# --- Configuration ---
CONFIG = {
    'INHALE_TIME': 4.0,
    'HOLD_AFTER_INHALE': 2.0,
    'EXHALE_TIME': 6.0,
    'HOLD_AFTER_EXHALE': 2.0,
    'MIN_LIGHT_RADIUS': 5.0,
    'MAX_LIGHT_RADIUS': 20.0,
    'CELL_SIZE': 10,
    'MAZE_SIZE': 100
}

CONFIG['TOTAL_CYCLE'] = (CONFIG['INHALE_TIME'] + CONFIG['HOLD_AFTER_INHALE'] + 
                         CONFIG['EXHALE_TIME'] + CONFIG['HOLD_AFTER_EXHALE'])
